@token = 31|Yh28i5xdJXSSlJbilFxmMVBjIDFG83ehbUOYGk1e6b175aa7

#### LOGIN
POST http://localhost:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "manoelmecat@gmail.com",
    "password": "12345678"
}

#### REGISTER
POST http://localhost:8000/api/auth/register
Content-Type: application/json
Accept: application/json

{
    "name": "Manoel",
    "email": "manoelmecatsd@gmail.com",
    "password": "12345678"
}

#### LOGOUT
POST http://localhost:8000/api/auth/logout
Accept: application/json
Authorization: Bearer {{token}}


#### ME
GET http://localhost:8000/api/auth/me
Accept: application/json
Authorization: Bearer {{token}}


